# Generated by Django 6.1.1 on 2026-10-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wyszukiwanie',
            options={'ordering': ['-data'], 'verbose_name': 'wyszukiwanie', 'verbose_name_plural': 'wyszukiwania'},
        ),
    ]
