# Generated by Django 6.1.1 on 2026-10-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_wyszukiwanie_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miejscowosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sym', models.CharField(max_length=7, unique=True)),
                ('nazwa', models.CharField(db_index=True, max_length=100)),
                ('wojewodztwo', models.CharField(max_length=30)),
                ('rodzaj', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'miejscowość',
                'verbose_name_plural': 'miejscowości',
                'ordering': ['nazwa'],
            },
        ),
    ]
